//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIVIOEntities : DbContext
    {
        public SIVIOEntities()
            : base("name=SIVIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_ACCION> TBL_ACCION { get; set; }
        public virtual DbSet<TBL_ADICCIONES> TBL_ADICCIONES { get; set; }
        public virtual DbSet<TBL_AGRESION> TBL_AGRESION { get; set; }
        public virtual DbSet<TBL_AGRESION_ATENCION_MEDICA> TBL_AGRESION_ATENCION_MEDICA { get; set; }
        public virtual DbSet<TBL_AGRESION_DETALLE_VIOLENCIA> TBL_AGRESION_DETALLE_VIOLENCIA { get; set; }
        public virtual DbSet<TBL_AGRESION_VIOLENCIA> TBL_AGRESION_VIOLENCIA { get; set; }
        public virtual DbSet<TBL_AGRESOR> TBL_AGRESOR { get; set; }
        public virtual DbSet<TBL_AGRESOR_MOTIVO_REGRESO> TBL_AGRESOR_MOTIVO_REGRESO { get; set; }
        public virtual DbSet<TBL_ARCHIVO> TBL_ARCHIVO { get; set; }
        public virtual DbSet<TBL_ATENCION> TBL_ATENCION { get; set; }
        public virtual DbSet<TBL_ATENCIONASESORIA> TBL_ATENCIONASESORIA { get; set; }
        public virtual DbSet<TBL_BITACORA> TBL_BITACORA { get; set; }
        public virtual DbSet<TBL_CATALOGO> TBL_CATALOGO { get; set; }
        public virtual DbSet<TBL_CONSULTA> TBL_CONSULTA { get; set; }
        public virtual DbSet<TBL_DIRECCION> TBL_DIRECCION { get; set; }
        public virtual DbSet<TBL_FAMILIAR_ACADEMICO> TBL_FAMILIAR_ACADEMICO { get; set; }
        public virtual DbSet<TBL_FAMILIAR_SALUD> TBL_FAMILIAR_SALUD { get; set; }
        public virtual DbSet<TBL_LABORAL> TBL_LABORAL { get; set; }
        public virtual DbSet<TBL_PERSONA> TBL_PERSONA { get; set; }
        public virtual DbSet<TBL_PERSONA_APOYO> TBL_PERSONA_APOYO { get; set; }
        public virtual DbSet<TBL_PERSONA_CONDICIONESPECIAL> TBL_PERSONA_CONDICIONESPECIAL { get; set; }
        public virtual DbSet<TBL_PERSONA_FAMILIAR> TBL_PERSONA_FAMILIAR { get; set; }
        public virtual DbSet<TBL_PERSONA_RED_APOYO> TBL_PERSONA_RED_APOYO { get; set; }
        public virtual DbSet<TBL_PERSONA_SALUD> TBL_PERSONA_SALUD { get; set; }
        public virtual DbSet<TBL_REFERENCIA> TBL_REFERENCIA { get; set; }
        public virtual DbSet<TBL_REFERENCIA_DETALLE> TBL_REFERENCIA_DETALLE { get; set; }
        public virtual DbSet<TBL_REGISTRO> TBL_REGISTRO { get; set; }
        public virtual DbSet<TBL_REGISTRO_CEAAM> TBL_REGISTRO_CEAAM { get; set; }
        public virtual DbSet<TBL_REGISTRO_COORDINACION> TBL_REGISTRO_COORDINACION { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_ROL_ACCION> TBL_ROL_ACCION { get; set; }
        public virtual DbSet<TBL_ROL_USUARIO> TBL_ROL_USUARIO { get; set; }
        public virtual DbSet<TBL_TELEFONO> TBL_TELEFONO { get; set; }
        public virtual DbSet<TBL_UNIDAD> TBL_UNIDAD { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual DbSet<TBL_VALOR_CATALOGO> TBL_VALOR_CATALOGO { get; set; }
    }
}
