//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SIVIOEntities : DbContext
    {
        public SIVIOEntities()
            : base("name=SIVIOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBL_ACCION> TBL_ACCION { get; set; }
        public virtual DbSet<TBL_ADICCIONES> TBL_ADICCIONES { get; set; }
        public virtual DbSet<TBL_AGRESION> TBL_AGRESION { get; set; }
        public virtual DbSet<TBL_AGRESION_ATENCION_MEDICA> TBL_AGRESION_ATENCION_MEDICA { get; set; }
        public virtual DbSet<TBL_AGRESION_CATEGORIA_RIESGO> TBL_AGRESION_CATEGORIA_RIESGO { get; set; }
        public virtual DbSet<TBL_AGRESION_CATEGORIZACION_RIESGO> TBL_AGRESION_CATEGORIZACION_RIESGO { get; set; }
        public virtual DbSet<TBL_AGRESION_DETALLE_VIOLENCIA> TBL_AGRESION_DETALLE_VIOLENCIA { get; set; }
        public virtual DbSet<TBL_AGRESION_IMPACTO_VIOLENCIA> TBL_AGRESION_IMPACTO_VIOLENCIA { get; set; }
        public virtual DbSet<TBL_AGRESION_VIOLENCIA> TBL_AGRESION_VIOLENCIA { get; set; }
        public virtual DbSet<TBL_AGRESOR> TBL_AGRESOR { get; set; }
        public virtual DbSet<TBL_AGRESOR_ADICCIONES> TBL_AGRESOR_ADICCIONES { get; set; }
        public virtual DbSet<TBL_AGRESOR_MOTIVO_REGRESO> TBL_AGRESOR_MOTIVO_REGRESO { get; set; }
        public virtual DbSet<TBL_ARCHIVO> TBL_ARCHIVO { get; set; }
        public virtual DbSet<TBL_ATENCION> TBL_ATENCION { get; set; }
        public virtual DbSet<TBL_ATENCION_LEGAL> TBL_ATENCION_LEGAL { get; set; }
        public virtual DbSet<TBL_ATENCION_LEGAL_DETALLE> TBL_ATENCION_LEGAL_DETALLE { get; set; }
        public virtual DbSet<TBL_ATENCION_PSICOLOGICA> TBL_ATENCION_PSICOLOGICA { get; set; }
        public virtual DbSet<TBL_ATENCION_PSICOLOGICA_DETALLE> TBL_ATENCION_PSICOLOGICA_DETALLE { get; set; }
        public virtual DbSet<TBL_ATENCION_TRABAJOSOCIAL> TBL_ATENCION_TRABAJOSOCIAL { get; set; }
        public virtual DbSet<TBL_ATENCION_TRABAJOSOCIAL_DETALLE> TBL_ATENCION_TRABAJOSOCIAL_DETALLE { get; set; }
        public virtual DbSet<TBL_BITACORA> TBL_BITACORA { get; set; }
        public virtual DbSet<TBL_CATALOGO> TBL_CATALOGO { get; set; }
        public virtual DbSet<TBL_CONSULTA> TBL_CONSULTA { get; set; }
        public virtual DbSet<TBL_DIRECCION> TBL_DIRECCION { get; set; }
        public virtual DbSet<TBL_FAMILIAR_ACADEMICO> TBL_FAMILIAR_ACADEMICO { get; set; }
        public virtual DbSet<TBL_FAMILIAR_SALUD> TBL_FAMILIAR_SALUD { get; set; }
        public virtual DbSet<TBL_INTERVENCION> TBL_INTERVENCION { get; set; }
        public virtual DbSet<TBL_INTERVENCION_ACOM_PROFESIONAL> TBL_INTERVENCION_ACOM_PROFESIONAL { get; set; }
        public virtual DbSet<TBL_INTERVENCION_COADYUVANCIA> TBL_INTERVENCION_COADYUVANCIA { get; set; }
        public virtual DbSet<TBL_INTERVENCION_COADYUVANCIA_DETALLE> TBL_INTERVENCION_COADYUVANCIA_DETALLE { get; set; }
        public virtual DbSet<TBL_INTERVENCION_COORDINACION_INTERINSTITUCIONAL> TBL_INTERVENCION_COORDINACION_INTERINSTITUCIONAL { get; set; }
        public virtual DbSet<TBL_INTERVENCION_CRITERIO_EXPERTO> TBL_INTERVENCION_CRITERIO_EXPERTO { get; set; }
        public virtual DbSet<TBL_INTERVENCION_CRITERIO_EXPERTO_DETALLE> TBL_INTERVENCION_CRITERIO_EXPERTO_DETALLE { get; set; }
        public virtual DbSet<TBL_INTERVENCION_INTERDISCIPLINARIA> TBL_INTERVENCION_INTERDISCIPLINARIA { get; set; }
        public virtual DbSet<TBL_INTERVENCION_PRC_PSICOSCEDUCATIVO> TBL_INTERVENCION_PRC_PSICOSCEDUCATIVO { get; set; }
        public virtual DbSet<TBL_INTERVENCION_PROCESO_GRUPAL> TBL_INTERVENCION_PROCESO_GRUPAL { get; set; }
        public virtual DbSet<TBL_INTERVENCION_RED_APOYO> TBL_INTERVENCION_RED_APOYO { get; set; }
        public virtual DbSet<TBL_INTERVENCION_TALLER> TBL_INTERVENCION_TALLER { get; set; }
        public virtual DbSet<TBL_INTERVENCION_TESTIMONIO_EXPERTO> TBL_INTERVENCION_TESTIMONIO_EXPERTO { get; set; }
        public virtual DbSet<TBL_LABORAL> TBL_LABORAL { get; set; }
        public virtual DbSet<TBL_PERSONA> TBL_PERSONA { get; set; }
        public virtual DbSet<TBL_PERSONA_APOYO> TBL_PERSONA_APOYO { get; set; }
        public virtual DbSet<TBL_PERSONA_CONDICIONESPECIAL> TBL_PERSONA_CONDICIONESPECIAL { get; set; }
        public virtual DbSet<TBL_PERSONA_FAMILIAR> TBL_PERSONA_FAMILIAR { get; set; }
        public virtual DbSet<TBL_PERSONA_RED_APOYO> TBL_PERSONA_RED_APOYO { get; set; }
        public virtual DbSet<TBL_PERSONA_SALUD> TBL_PERSONA_SALUD { get; set; }
        public virtual DbSet<TBL_REFERENCIA> TBL_REFERENCIA { get; set; }
        public virtual DbSet<TBL_REFERENCIA_DETALLE> TBL_REFERENCIA_DETALLE { get; set; }
        public virtual DbSet<TBL_REGISTRO> TBL_REGISTRO { get; set; }
        public virtual DbSet<TBL_REGISTRO_CEAAM> TBL_REGISTRO_CEAAM { get; set; }
        public virtual DbSet<TBL_REGISTRO_COORDINACION> TBL_REGISTRO_COORDINACION { get; set; }
        public virtual DbSet<TBL_REGISTRO_TIPIFICACION_VIOLENCIA> TBL_REGISTRO_TIPIFICACION_VIOLENCIA { get; set; }
        public virtual DbSet<TBL_ROL> TBL_ROL { get; set; }
        public virtual DbSet<TBL_ROL_ACCION> TBL_ROL_ACCION { get; set; }
        public virtual DbSet<TBL_ROL_TIPO_ATENCION> TBL_ROL_TIPO_ATENCION { get; set; }
        public virtual DbSet<TBL_ROL_USUARIO> TBL_ROL_USUARIO { get; set; }
        public virtual DbSet<TBL_TELEFONO> TBL_TELEFONO { get; set; }
        public virtual DbSet<TBL_UNIDAD> TBL_UNIDAD { get; set; }
        public virtual DbSet<TBL_USUARIO> TBL_USUARIO { get; set; }
        public virtual DbSet<TBL_VALOR_CATALOGO> TBL_VALOR_CATALOGO { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual ObjectResult<SP_BUSCAR_EXPEDIENTE_CEEAM_Result> SP_BUSCAR_EXPEDIENTE_CEEAM(string vC_TERMINOBUSQUEDA)
        {
            var vC_TERMINOBUSQUEDAParameter = vC_TERMINOBUSQUEDA != null ?
                new ObjectParameter("VC_TERMINOBUSQUEDA", vC_TERMINOBUSQUEDA) :
                new ObjectParameter("VC_TERMINOBUSQUEDA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSCAR_EXPEDIENTE_CEEAM_Result>("SP_BUSCAR_EXPEDIENTE_CEEAM", vC_TERMINOBUSQUEDAParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<SP_LISTAR_ATENCIONES_Result> SP_LISTAR_ATENCIONES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_ATENCIONES_Result>("SP_LISTAR_ATENCIONES");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SP_LISTAR_PROFESIONALES_Result> SP_LISTAR_PROFESIONALES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_PROFESIONALES_Result>("SP_LISTAR_PROFESIONALES");
        }
    
        public virtual ObjectResult<SP_LISTAR_CATEGORIAS_VIOLENCIA_CUESTIONARIO_Result> SP_LISTAR_CATEGORIAS_VIOLENCIA_CUESTIONARIO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LISTAR_CATEGORIAS_VIOLENCIA_CUESTIONARIO_Result>("SP_LISTAR_CATEGORIAS_VIOLENCIA_CUESTIONARIO");
        }
    }
}
