//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REFERENCIA
    {
        public System.Guid PK_REFERENCIA { get; set; }
        public int FK_TIPOREFERENCIA { get; set; }
        public Nullable<System.Guid> FK_REGISTRO { get; set; }
        public int FK_INSTITUCIONORIGEN { get; set; }
        public int FK_INSTITUCIONDESTINO { get; set; }
        public Nullable<System.Guid> FK_INTERVENCION { get; set; }
        public System.DateTime DT_FECHAREFERENCIA { get; set; }
    
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO1 { get; set; }
    }
}
