//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INTERVENCION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_INTERVENCION()
        {
            this.TBL_INTERVENCION_ACOM_PROFESIONAL = new HashSet<TBL_INTERVENCION_ACOM_PROFESIONAL>();
            this.TBL_INTERVENCION_COORDINACION_INTERINSTITUCIONAL = new HashSet<TBL_INTERVENCION_COORDINACION_INTERINSTITUCIONAL>();
            this.TBL_INTERVENCION_INTERDISCIPLINARIA = new HashSet<TBL_INTERVENCION_INTERDISCIPLINARIA>();
            this.TBL_INTERVENCION_PRC_PSICOSCEDUCATIVO = new HashSet<TBL_INTERVENCION_PRC_PSICOSCEDUCATIVO>();
            this.TBL_INTERVENCION_PROCESO_GRUPAL = new HashSet<TBL_INTERVENCION_PROCESO_GRUPAL>();
            this.TBL_INTERVENCION_RED_APOYO = new HashSet<TBL_INTERVENCION_RED_APOYO>();
            this.TBL_INTERVENCION_TALLER = new HashSet<TBL_INTERVENCION_TALLER>();
            this.TBL_INTERVENCION_TESTIMONIO_EXPERTO = new HashSet<TBL_INTERVENCION_TESTIMONIO_EXPERTO>();
        }
    
        public System.Guid PK_INTERVENCION { get; set; }
        public Nullable<int> FK_PERSONA { get; set; }
        public int FK_TIPOINTERVENCION { get; set; }
        public int FK_PROFESIONALENCARGADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_ACOM_PROFESIONAL> TBL_INTERVENCION_ACOM_PROFESIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_COORDINACION_INTERINSTITUCIONAL> TBL_INTERVENCION_COORDINACION_INTERINSTITUCIONAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_INTERDISCIPLINARIA> TBL_INTERVENCION_INTERDISCIPLINARIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_PRC_PSICOSCEDUCATIVO> TBL_INTERVENCION_PRC_PSICOSCEDUCATIVO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_PROCESO_GRUPAL> TBL_INTERVENCION_PROCESO_GRUPAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_RED_APOYO> TBL_INTERVENCION_RED_APOYO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_TALLER> TBL_INTERVENCION_TALLER { get; set; }
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_INTERVENCION_TESTIMONIO_EXPERTO> TBL_INTERVENCION_TESTIMONIO_EXPERTO { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
    }
}
