//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ARCHIVO
    {
        public System.Guid PK_ARCHIVO { get; set; }
        public System.Guid FK_REGISTRO { get; set; }
        public string VC_ENLACE { get; set; }
        public string VC_NOMBRE { get; set; }
    
        public virtual TBL_REGISTRO TBL_REGISTRO { get; set; }
    }
}
