//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_CONSULTA
    {
        public System.Guid PK_CONSULTA { get; set; }
        public System.Guid FK_REGISTRO { get; set; }
        public Nullable<bool> B_INGRESOCEEAM { get; set; }
        public Nullable<int> FK_RAZONRECHAZO { get; set; }
        public string VC_OBSERVACIONES { get; set; }
        public Nullable<bool> B_REINGRESOCEEAM { get; set; }
        public Nullable<int> FK_TIPOCEEAMREINGRESO { get; set; }
        public Nullable<int> FK_TIPOCEEAMINGRESO { get; set; }
        public string VC_CONTACTOCEEAM { get; set; }
        public Nullable<int> FK_ENTIDADTRASLADA { get; set; }
        public Nullable<System.TimeSpan> TM_TRASLADOAPROX { get; set; }
    
        public virtual TBL_REGISTRO TBL_REGISTRO { get; set; }
    }
}
