//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AGRESION_CATEGORIA_RIESGO
    {
        public System.Guid PK_AGRESIONVALORACIONRIESGO { get; set; }
        public System.Guid FK_AGRESION { get; set; }
        public int FK_TIPORESPUESTA { get; set; }
        public int FK_OBSERVACION { get; set; }
    
        public virtual TBL_AGRESION TBL_AGRESION { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
