//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONA_CONDICIONESPECIAL
    {
        public int FK_PERSONA { get; set; }
        public int FK_CONDICIONESPECIAL { get; set; }
        public System.Guid PK_CONDICIONESPECIAL { get; set; }
    
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
        public virtual TBL_PERSONA TBL_PERSONA { get; set; }
    }
}
