//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROL_USUARIO
    {
        public int FK_USUARIO { get; set; }
        public int FK_ROL { get; set; }
        public System.Guid PK_ROLUSUAIO { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual TBL_ROL TBL_ROL { get; set; }
    }
}
