//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REGISTRO_CEAAM
    {
        public System.Guid PK_REGISTRO_CEAAM { get; set; }
        public System.Guid FK_REGISTRO { get; set; }
        public int FK_TIPOINGRESO { get; set; }
        public string VC_OBSERVACIONESINGRESO { get; set; }
        public System.DateTime DT_FECHAINGRESO { get; set; }
        public string VC_PERSONARECIBE { get; set; }
        public string VC_NUMEROFAMILIA { get; set; }
        public Nullable<System.DateTime> DT_FECHAEGRESO { get; set; }
        public Nullable<int> FK_TIPOEGRESO { get; set; }
        public string VC_OBSERVACIONESEGRESO { get; set; }
        public int FK_PROVINCIA { get; set; }
        public int FK_CANTON { get; set; }
        public int FK_DISTRITO { get; set; }
        public string VC_DESTINOEXTRANJERO { get; set; }
        public bool B_KITEMERGENCIA { get; set; }
        public int FK_VALORACIONRIESGO { get; set; }
        public bool B_PROGRAMAOAPVD { get; set; }
        public string VC_JUSTIFICACION { get; set; }
<<<<<<< HEAD
        public bool B_CASOACTIVO { get; set; }
=======
>>>>>>> origin/coavif_ee
    
        public virtual TBL_REGISTRO TBL_REGISTRO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO1 { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO2 { get; set; }
    }
}
