//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AGRESOR_MOTIVO_REGRESO
    {
        public int FK_AGRESOR { get; set; }
        public int FK_MOTIVOREGRESO { get; set; }
        public System.Guid PK_MOTIVOREGRESO { get; set; }
    
        public virtual TBL_AGRESOR TBL_AGRESOR { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
