//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ROL_TIPO_ATENCION
    {
        public System.Guid PK_ROLTIPOATENCION { get; set; }
        public int FK_ROL { get; set; }
        public int FK_TIPOATENCION { get; set; }
    
        public virtual TBL_ROL TBL_ROL { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
