//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ATENCIONASESORIA
    {
        public System.Guid FK_ATENCION { get; set; }
        public int FK_TIPOASESORIA { get; set; }
        public System.Guid PK_ASESORIA { get; set; }
    
        public virtual TBL_ATENCION TBL_ATENCION { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
