//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INTERVENCION_TALLER
    {
        public System.Guid PK_TALLER { get; set; }
        public Nullable<System.Guid> FK_INTERVENCION { get; set; }
        public string VC_TIPO { get; set; }
        public Nullable<System.DateTime> VC_FECHA { get; set; }
        public string VC_PERIODOPARTICIPACION { get; set; }
        public string VC_OBSERVACIONES { get; set; }
    
        public virtual TBL_INTERVENCION TBL_INTERVENCION { get; set; }
    }
}
