//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INTERVENCION_CRITERIO_EXPERTO_DETALLE
    {
        public System.Guid PK_CRITERIOEXPERTODETALLE { get; set; }
        public int FK_TIPODETALLECRITERIOEXPERTO { get; set; }
        public System.Guid FK_CRITERIOEXPERTO { get; set; }
    
        public virtual TBL_INTERVENCION_CRITERIO_EXPERTO TBL_INTERVENCION_CRITERIO_EXPERTO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
