//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_REFERENCIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_REFERENCIA()
        {
            this.TBL_REFERENCIA_DETALLE = new HashSet<TBL_REFERENCIA_DETALLE>();
        }
    
        public System.Guid PK_REFERENCIA { get; set; }
        public int FK_TIPOREFERENCIA { get; set; }
        public System.Guid FK_REGISTRO { get; set; }
        public int FK_INSTITUCIONORIGEN { get; set; }
        public int FK_INSTITUCIONDESTINO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_REFERENCIA_DETALLE> TBL_REFERENCIA_DETALLE { get; set; }
        public virtual TBL_REGISTRO TBL_REGISTRO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO1 { get; set; }
    }
}
