//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INTERVENCION_INTERDISCIPLINARIA
    {
        public System.Guid PK_INTERDISCIPLINARIA { get; set; }
        public System.Guid FK_INTERVENCION { get; set; }
        public System.DateTime DT_FECHA { get; set; }
        public string VC_PERSONASPARTICIPAN { get; set; }
    
        public virtual TBL_INTERVENCION TBL_INTERVENCION { get; set; }
    }
}
