//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AGRESION_DETALLE_VIOLENCIA
    {
        public System.Guid FK_AGRESIONVIOLENCIA { get; set; }
        public int FK_SITUACIONVIOLENCIA { get; set; }
        public System.Guid PK_SITUACIONVIOLENCIA { get; set; }
    
        public virtual TBL_AGRESION_VIOLENCIA TBL_AGRESION_VIOLENCIA { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
