//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PERSONA_FAMILIAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_PERSONA_FAMILIAR()
        {
            this.TBL_FAMILIAR_ACADEMICO = new HashSet<TBL_FAMILIAR_ACADEMICO>();
            this.TBL_FAMILIAR_SALUD = new HashSet<TBL_FAMILIAR_SALUD>();
        }
    
        public System.Guid PK_FAMILIAR { get; set; }
        public Nullable<int> PK_PERSONA { get; set; }
        public string VC_NOMBRE { get; set; }
        public string VC_APELLIDO1 { get; set; }
        public string VC_APELLIDO2 { get; set; }
        public int FK_NACIONALIDAD { get; set; }
        public int FK_PARENTESCOPERSONA { get; set; }
        public int FK_PARENTESCOAGRESOR { get; set; }
        public bool B_ABUSOSEXUAL { get; set; }
        public bool B_DENUNCIAABUSOSEXUAL { get; set; }
        public System.DateTime DT_FECHANACIMIENTO { get; set; }
        public int FK_OCUPACION { get; set; }
        public int FK_ESCOLARIDAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FAMILIAR_ACADEMICO> TBL_FAMILIAR_ACADEMICO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_FAMILIAR_SALUD> TBL_FAMILIAR_SALUD { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
        public virtual TBL_CATALOGO TBL_CATALOGO { get; set; }
    }
}
