//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIVIO.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_INTERVENCION_COADYUVANCIA_DETALLE
    {
        public System.Guid PK_COADYUVANCIADETALLE { get; set; }
        public System.Guid FK_COADYUVANCIA { get; set; }
        public int FK_TIPODETALLECOADYUVANCIA { get; set; }
    
        public virtual TBL_INTERVENCION_COADYUVANCIA TBL_INTERVENCION_COADYUVANCIA { get; set; }
        public virtual TBL_VALOR_CATALOGO TBL_VALOR_CATALOGO { get; set; }
    }
}
